### ISSUE TITLE
No build instructions in README

### ISSUE THREAD

**Issue by mudmov** [vsedov/auto_attendance#1]
Considering that you have produced such invaluable software, it is almost criminal to not have build instructions in your README. Please add.

**Comment by vsedov** [comment]
code is quite bad, although I understand. later this week, il implement a readme. 

for now if u want to run it , would recommend setting up crone jobs

**Comment by mbeps** [comment]
@mabdulker maybe you can be of use and make one

**Comment by vsedov** [comment]
ive added simple instructions that should be of use later down the line. 

Please refer to #2  and set up your keys according. And [DigitalOcean](https://www.digitalocean.com/) as well if you wish or any other server.
